input_nc: 3
output_nc: 1
name: "your_weight_name"
paired: True
netG: "sit"
batch_size: 1
gpu_ids: "0"
phase: "test"
num_test: 1000000
B_modality: "random"
train_number: 100000
get_mask: False
direction: "AtoB"
model: "pix2pix"
dataset_mode: "brain_3D_random_mod"
amp: False
single_folder: False
isTrain: False
checkpoints_dir: "checkpoints"
preprocess: "resize_and_crop"
lambda_perceptual: 1.5
ngf: 64
normG: 'instance'
no_dropout: True
init_type: 'kaiming'
init_gain: 0.02
no_antialias: False
no_antialias_up: False
bayesian: False
max_dataset_size: 9223372036854775807
epoch: "latest"
checkpoint_path: NULL
verbose: False
eval: True
for_segmentation: False